### ISSUE TITLE
Addition in data category - RxFirebase

### ISSUE THREAD

**Issue by spirosoik** [zsoltk/RxAndroidLibs#17]
You can add an Rx implementation of firebase database. Check here https://github.com/spirosoik/Android-RxFirebase I would glad to hear your opinion. Thanks

**Comment by zsoltk** [comment]
Hey @spirosoik , is this relevant anymore? I see the "NOT SUPPORTED ANYMORE" notice in your readme. Is the ezhome fork ok? Does it support the Google integrated Firebase? If you feel so, please create a PR, I'm closing the issue here.

**Comment by spirosoik** [comment]
@zsoltk I added the `Not Supported` 1 week before. Everything is moved in ezhome repository. 

This implementation without new library supports new Firebase and it's tested in a production env.  I just raised a PR for ezhome with new Firebase. So you can add it.
